 # * Copyright (c) 2017-present, Jembi Health Systems NPC.
 # * All rights reserved.
 # *
 # * This source code is licensed under the BSD-style license found in the
 # * LICENSE file in the root directory of this source tree.
 
language: node_js
sudo: false
node_js:
  - "6"
services:
  - mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
env:
  - CXX=g++-4.8
after_success:
  - npm run test:upload-cov
  - npm run test:load
addon:
  srcclr: true