language: node_js
sudo: false
node_js:
  - "6"
addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
after_success:
  - npm run test:upload-cov
addon:
  srcclr: true