version: '3'

services:
  mongo:
    container_name: hearth-mongo
    image: mongo:3.4
    volumes:
      - ./hearth_data/mongo:/data/db
    
  api:
    container_name: hearth-api
    build: ../../.
    ports:
      - "3447:3447"
    depends_on:
      - mongo
    restart: unless-stopped
    volumes:
       - ../../:/src/hearth/
       - /src/hearth/node_modules